- name: Install necessary package
  apt:
    pkg:
      - ca-certificates
      - gnupg
      - uidmap
      - dbus-user-session
      - curl
  become: true

- name: Reset SSH connection
  meta: reset_connection

- name: Add Docker GPG key
  shell: |
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    creates: "/etc/apt/keyrings/docker.asc"
  become: true

- name: Add Docker repository to apt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Install Docker package
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce-rootless-extras
    update_cache: yes
  become: true

- name: Allow docker start on system boot
  command: loginctl enable-linger lostops
  become: true

- name: Install rootless Docker
  command:
  args:
    cmd: dockerd-rootless-setuptool.sh install
    creates: "/home/lostops/.docker/config.json"
  environment:
    XDG_RUNTIME_DIR: "/run/user/1500"
  become: true
  become_user: lostops

- name: Ensure PATH and DOCKER_HOST are set in ~/.bashrc
  lineinfile:
    path: "/home/lostops/.bashrc"
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - "export PATH=/home/lostops/bin:$PATH"
    - "export DOCKER_HOST=unix:///run/user/1500/docker.sock"
  become: true
  become_user: lostops

- name: Reset SSH connection
  meta: reset_connection

- name: Launch Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    scope: user
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1500/bus"
    XDG_RUNTIME_DIR: "/run/user/1500"
  become: true
  become_user: lostops
