---
- name: Ensure Docker is installed
  ansible.builtin.package:
    name: docker
    state: present

- name: Pull Grafana Docker image
  community.general.docker_image:
    name: grafana/grafana
    source: pull

- name: Run Grafana container
  community.general.docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - "/path/to/grafana/data:/var/lib/grafana"
