---
# tasks file for ufw_install
- name: Install ufw
  apt:
    name: ufw
    state: latest
  become: true

- name: Configure UFW to allow SSH
  ufw:
    rule: allow
    port: '22'
    state: enabled
  become: true

- name: Configure UFW to allow docker daemon
  ufw:
    rule: allow
    port: '2375'
    state: enabled
  become: true

- name: Configure UFW to allow docker daemon
  ufw:
    rule: allow
    port: '2376'
    state: enabled
  become: true

- name: Configure UFW to allow port 53
  ufw:
    rule: allow
    port: '53'
    state: enabled
  become: true

- name: Configure UFW to allow port 5000
  ufw:
    rule: allow
    port: '5000'
    state: enabled
  become: true

- name: Allow all access from RFC1918 networks to this host
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  become: true
