- name: Restart cadvisor-exporter
  become: true
  become_user: lostops
  systemd:
    name: "{{ cadvisor_exporter_service_name }}.service"
    daemon_reload: yes
    state: restarted
    scope: user
  listen: restart cadvisor-exporter