---
- name: Making chaos on database
  hosts: database
  tags: database
  remote_user: lostops
  roles:
    - shutdown_random

- name: Making chaos on database
  hosts: web
  tags: web
  remote_user: lostops
  roles:
    - shutdown_random

- name: Making chaos on database
  hosts: docker
  tags: docker
  remote_user: lostops
  roles:
    - shutdown_random
