- name: Configure Database Server
  hosts: database
  tags: database
  vars_files:
    - ./vault.yml # "import" vault file
  remote_user: admuser # defines user used, by default Ansible will ssh via root
  roles: # roles will be executed in order
    - create_user
    - add_ssh_keys
    - install_docker
    - node_exporter
    - install_mysql

- name: Configure Docker Server
  hosts: docker
  tags: docker
  vars_files:
    - ./vault.yml # "import" vault file
  remote_user: admuser # defines user used, by default Ansible will ssh via root
  roles: # roles will be executed in order
    - create_user
    - add_ssh_keys
    - install_docker
    - node_exporter
    - cadvisor_exporter
    - install_prometheus
    - install_grafana

- name: Configure Web Server
  hosts: web
  tags: web
  vars_files:
    - ./vault.yml # "import" vault file
  remote_user: admuser # defines user used, by default Ansible will ssh via root
  roles: # roles will be executed in order
    - create_user
    - add_ssh_keys
    - install_docker
    - node_exporter
    - cadvisor_exporter
