- name: Create data volume if not exist
  become: true
  become_user: lostops
  docker_volume:
    docker_host: "unix:///run/user/1500/docker.sock"
    name: mysql_data

- name: Run mysql container
  become: true
  become_user: lostops
  docker_container:
    user: root
    docker_host: "unix:///run/user/1500/docker.sock"
    image: "mysql:latest"
    name: mysql
    detach: true
    restart_policy: always
    # Traefik labels
    labels:
      traefik.enable: "true"
      traefik.http.routers.mysql.entrypoints: "websecure"
      traefik.http.routers.mysql.rule: "Host(`db.lostops.notmuji.com`)"
    ports:
      - "3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_USER: "{{ mysql_username }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: "lostopsdb"
