- name: Install python3-requests package
  apt:
    name: python3-requests
    state: present

- name: Install python3-docker package
  apt:
    name: python3-docker
    state: present

- name: Pull Traefik Docker image
  docker_image:
    name: traefik
    state: present

- name: Create /etc/traefik directory if it doesn't exist
  file:
    path: "/etc/traefik"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Insert file
  template:
    src: /home/broot4rce/Desktop/T-NSA-800/roles/deploy_traefik_in_docker/templates/traefik_template.yml.j2
    dest: /etc/traefik/traefik.yml

- name: Create Docker network for Traefik if it doesn't exist
  docker_network:
    name: traefik_network

- name: Run Traefik container
  docker_container:
    name: traefik
    image: traefik
    state: started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "unix:////run/user/1500/docker.sock:/var/run/docker.sock"
      - "/etc/traefik:/etc/traefik"
    networks:
      - name: traefik_network
