- name: Create user with password and all database privileges
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_port: 3306
    login_host: 127.0.0.1
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

- name: Create mysql-exporter container
  become: true
  become_user: lostops
  docker_container:
    user: root
    docker_host: "unix:///run/user/1500/docker.sock"
    name: "{{ mysql_exporter_service_name }}"
    command: "{{ mysql_exporter_args }}"
    detach: true
    image: "{{ mysql_exporter_image }}"
    networks:
      - name: traefik_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.mysql-exporter.entrypoints: "websecure"
      traefik.http.routers.mysql-exporter.rule: "Host(`app-database.mysql-exporter.lostops.notmuji.com`)"
    ports:
      - "9104"
    state: started
    volumes:
      - "/:/host:ro,rslave"
  notify: restart mysql-exporter

- name: Create mysql-exporter service file
  become: true
  become_user: lostops
  template:
    dest: "/home/lostops/.config/systemd/user/{{ mysql_exporter_service_name }}.service"
    src: "roles/mysql_exporter/templates/mysql-exporter.service.j2"
    mode: 0664
  notify: restart mysql-exporter

- name: Enable mysql-exporter service
  become: true
  become_user: lostops
  service:
    name: "{{ mysql_exporter_service_name }}.service"
    state: started
    enabled: yes
    scope: user
