- name: Configure UFW incoming request for DB Server
  ufw:
    rule: allow
    direction: in
    port: "{{ db_port }}"
    from_ip: 
      - "{{ monitoring_ip }}"
      - "{{ backend_ip }}"


- name: Configure UFW outcoming request for DB Server.
  ufw:
   rule: allow
   direction: out
   port: "{{ db_port }}"
   state: enabled